name: Merge to stage

on:
  push:
    branches:
    - test
  workflow_dispatch: #run manually

jobs:

  log_time:
    name: log the time of push
    runs-on: ubuntu-latest
    
    steps:
    - name: echoing date
      run: echo $(date +%Y%m%d%H%M)

    - uses: actions/create-github-app-token@v1
      id: milo-pr-merge-token
      with:
        app-id: ${{ secrets.CC_PR_MERGE_APP_ID }}
        private-key: ${{ secrets.CC_PR_MERGE_PRIVATE_KEY }}
        
    - name: Checkout repository
      uses: actions/checkout@v4

    - run: echo ${{ steps.milo-pr-merge-token.outputs.token }}
