name: Use perf-metrics PR comment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-comment:
    uses: adobecom/perf-metrics/.github/workflows/pr-comment-from-perf-metrics.yaml@main
